In [11]:
df.describe()

,ID_SUBCLASSE,VL_TOTAL,VL_QUOTA,VL_PATRIM_LIQ,CAPTC_DIA,RESG_DIA,NR_COTST
count,0.0,5.678340e+05,5.678340e+05,5.678340e+05,5.678340e+05,5.678340e+05,5.678340e+05
mean,NaN,4.257175e+08,2.148021e+04,4.245249e+08,2.422155e+06,2.228884e+06,9.841879e+02
std,NaN,2.880299e+09,1.295410e+06,2.877278e+09,5.538870e+07,4.950180e+07,1.635658e+04
min,NaN,-8.298310e+08,-5.940935e+03,-3.743481e+07,0.000000e+00,0.000000e+00,0.000000e+00
25%,NaN,1.562205e+07,1.214512e+00,1.554035e+07,0.000000e+00,0.000000e+00,1.000000e+00
50%,NaN,4.331932e+07,2.138757e+00,4.321707e+07,0.000000e+00,0.000000e+00,2.000000e+00
75%,NaN,1.539497e+08,2.521384e+01,1.531781e+08,0.000000e+00,0.000000e+00,1.500000e+01
max,NaN,1.613959e+11,2.013671e+08,1.613956e+11,9.083470e+09,1.399587e+10,1.176607e+06

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 567834 entries, 0 to 567833
Data columns (total 10 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   TP_FUNDO_CLASSE    567834 non-null  str
 1   CNPJ_FUNDO_CLASSE  567834 non-null  str
 2   ID_SUBCLASSE       0 non-null       float64
 3   DT_COMPTC          567834 non-null  str
 4   VL_TOTAL           567834 non-null  float64
 5   VL_QUOTA           567834 non-null  float64
 6   VL_PATRIM_LIQ      567834 non-null  float64
 7   CAPTC_DIA          567834 non-null  float64
 8   RESG_DIA           567834 non-null  float64
 9   NR_COTST           567834 non-null  int64
dtypes: float64(6), int64(1), str(3)
memory usage: 59.6 MB

In [9]:
df = pd.read_csv("../data/raw/inf_diario_fi_202401.csv", sep=";", encoding="latin1")
                 
print(f"Linhas: {df.shape[0]}")
print(f"Colunas: {df.shape[1]}")
df.head()

Linhas: 567834
Colunas: 10

,TP_FUNDO_CLASSE,CNPJ_FUNDO_CLASSE,ID_SUBCLASSE,DT_COMPTC,VL_TOTAL,VL_QUOTA,VL_PATRIM_LIQ,CAPTC_DIA,RESG_DIA,NR_COTST
0,FI,00.017.024/0001-53,NaN,2024-01-02,1136699.13,34.298860,1139708.10,0.0,0.0,1
1,FI,00.017.024/0001-53,NaN,2024-01-03,1137245.82,34.312303,1140154.80,0.0,0.0,1
2,FI,00.017.024/0001-53,NaN,2024-01-04,1137741.93,34.326023,1140610.71,0.0,0.0,1
3,FI,00.017.024/0001-53,NaN,2024-01-05,1138240.64,34.338221,1141016.02,0.0,0.0,1
4,FI,00.017.024/0001-53,NaN,2024-01-08,1138427.98,34.350495,1141423.89,0.0,0.0,1

In [7]:
import zipfile

with zipfile.ZipFile("../data/raw/inf_diario_fi_202401.zip", "r") as zip:
    zip.extractall("../data/raw")
    
print("Arquivo extraído")

Arquivo extraído

In [6]:
import requests
import os

url = "https://dados.cvm.gov.br/dados/FI/DOC/INF_DIARIO/DADOS/inf_diario_fi_202401.zip"

os.makedirs("../data/raw", exist_ok=True)

print("Baixando dados da CVW...")
response = requests.get(url)

with open ("../data/raw/inf_diario_fi_202401.zip", "wb") as f:
    f.write(response.content)
    
    
print("Download Concluído!")

Baixando dados da CVW...
Download Concluído!

# 📊 Análise Exploratória de Dados — Fundos de Investimento CVM

## Objetivo
Explorar os dados públicos da CVM para entender o comportamento dos fundos de investimento brasileiros.

## Perguntas que vamos responder
- Quantos fundos existem e quais os tipos?
- Como está distribuído o patrimônio líquido?
- Como evoluiu a captação ao longo do tempo?
- Existem dados faltando?

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

print(" Bibliotecas importadas com sucesso")

 Bibliotecas importadas com sucesso